name: Json Check

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the checking of index and manifest files
        uses: reviversmc/the-mod-index-validation@4.0.0