name: Json Check

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the checking of index and manifest files
        uses: reviversmc/the-mod-index-validation@3.0.0