name: Json Check

on:
  push:
    branches: [ main, next/*, legacy/*, v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Do the checking of index and manifest files
      uses: reviversmc/the-mod-index-validation@v1.0.0-1.0.0